---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - path: helm-controller.yaml
    target:
      kind: Deployment
      name: helm-controller
  - path: kustomize-controller.yaml
    target:
      kind: Deployment
      name: kustomize-controller
  - path: notification-controller.yaml
    target:
      kind: Deployment
      name: notification-controller
  - path: source-controller.yaml
    target:
      kind: Deployment
      name: source-controller
